# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_pb2 as file__pb2


class ClientHandlerStub(object):
    """The ClientHandler service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/ClientHandler/ListUsers',
                request_serializer=file__pb2.ListRequest.SerializeToString,
                response_deserializer=file__pb2.ListReply.FromString,
                )
        self.Login = channel.unary_unary(
                '/ClientHandler/Login',
                request_serializer=file__pb2.LoginRequest.SerializeToString,
                response_deserializer=file__pb2.LoginReply.FromString,
                )
        self.Logout = channel.unary_unary(
                '/ClientHandler/Logout',
                request_serializer=file__pb2.LogoutRequest.SerializeToString,
                response_deserializer=file__pb2.LogoutReply.FromString,
                )
        self.Delete = channel.unary_unary(
                '/ClientHandler/Delete',
                request_serializer=file__pb2.DeleteRequest.SerializeToString,
                response_deserializer=file__pb2.DeleteReply.FromString,
                )
        self.Check = channel.unary_unary(
                '/ClientHandler/Check',
                request_serializer=file__pb2.CheckRequest.SerializeToString,
                response_deserializer=file__pb2.CheckReply.FromString,
                )
        self.Upload = channel.stream_unary(
                '/ClientHandler/Upload',
                request_serializer=file__pb2.UploadRequest.SerializeToString,
                response_deserializer=file__pb2.UploadReply.FromString,
                )
        self.Sync = channel.unary_stream(
                '/ClientHandler/Sync',
                request_serializer=file__pb2.SyncRequest.SerializeToString,
                response_deserializer=file__pb2.SyncReply.FromString,
                )


class ClientHandlerServicer(object):
    """The ClientHandler service definition.
    """

    def ListUsers(self, request, context):
        """Lists users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Requests to Login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Requests to Logout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Attempts to delete account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Checks a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request_iterator, context):
        """Attempts to upload a file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Attempts to sync files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=file__pb2.ListRequest.FromString,
                    response_serializer=file__pb2.ListReply.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=file__pb2.LoginRequest.FromString,
                    response_serializer=file__pb2.LoginReply.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=file__pb2.LogoutRequest.FromString,
                    response_serializer=file__pb2.LogoutReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=file__pb2.DeleteRequest.FromString,
                    response_serializer=file__pb2.DeleteReply.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=file__pb2.CheckRequest.FromString,
                    response_serializer=file__pb2.CheckReply.SerializeToString,
            ),
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=file__pb2.UploadRequest.FromString,
                    response_serializer=file__pb2.UploadReply.SerializeToString,
            ),
            'Sync': grpc.unary_stream_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=file__pb2.SyncRequest.FromString,
                    response_serializer=file__pb2.SyncReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientHandler(object):
    """The ClientHandler service definition.
    """

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientHandler/ListUsers',
            file__pb2.ListRequest.SerializeToString,
            file__pb2.ListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientHandler/Login',
            file__pb2.LoginRequest.SerializeToString,
            file__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientHandler/Logout',
            file__pb2.LogoutRequest.SerializeToString,
            file__pb2.LogoutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientHandler/Delete',
            file__pb2.DeleteRequest.SerializeToString,
            file__pb2.DeleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientHandler/Check',
            file__pb2.CheckRequest.SerializeToString,
            file__pb2.CheckReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ClientHandler/Upload',
            file__pb2.UploadRequest.SerializeToString,
            file__pb2.UploadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ClientHandler/Sync',
            file__pb2.SyncRequest.SerializeToString,
            file__pb2.SyncReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
