# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatService = channel.stream_stream(
                '/chatserver.Services/ChatService',
                request_serializer=chat__pb2.FromClient.SerializeToString,
                response_deserializer=chat__pb2.FromServer.FromString,
                )


class ServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatService(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatService': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatService,
                    request_deserializer=chat__pb2.FromClient.FromString,
                    response_serializer=chat__pb2.FromServer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatserver.Services', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Services(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatService(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/chatserver.Services/ChatService',
            chat__pb2.FromClient.SerializeToString,
            chat__pb2.FromServer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
